### ISSUE TITLE
How to fix the CD problem:

### ISSUE THREAD

**Issue by yum13241** [AFellowSpeedrunner/SmolXP#4]
The problem:
> I forgot how to disable this so I'll release a 1.2 if I figure it out. IF YOU BOOT INTO THE CD. IT. WILL. WIPE. YOUR DRIVE. It's somehow set it do that due to unattended setup. I need to fix this so please if you install this new version that you better hope that if you accidentally boot into it you didn't have anything important on the drive!!!

Use any mode that is not "Fully unattended" in nLite.

**Comment by AFellowSpeedrunner** [comment]
Thanks, I will fix this issue soon when I have time.

**Comment by AFellowSpeedrunner** [comment]
H

**Comment by yum13241** [comment]
I'll fix it for you, thankfully you kept the session on the ISO. By the time you see this, there will be a link.

If you think I'm about to package malware, then revert the one change I made and see if the checksum matches.

**Comment by AFellowSpeedrunner** [comment]
Thanks for helping me! I wanted to give all the files and source I used for this project in case others wanted to help, turns out that was the right decision. Your help is very much appreciated!

**Comment by yum13241** [comment]
You're welcome.

**Comment by yum13241** [comment]
There's a broken RunOnce entry that tries to run WPADISABLE.BAT that I can't fix, but here you go!
https://mega.nz/file/GIQhAA7K#46AVwnsIjPjw-3Y9l4EQBji8lsVfQk5rVGhGUyVnXdA

**Comment by AFellowSpeedrunner** [comment]
I'm gonna check the build on a VM to make sure it works. I had no knowledge of LiteXP actually. This build of Windows XP I had used was on my hard drive full of things. That build I used I downloaded years ago, around 2016/17 from archive.org or somewhere to be exact which has worked time and time again perfectly. I do use MalwareWatch for Windows beta's mainly, so don't worry I trust you completely here. About that product key being the ONLY product key works with TinyXP, that product key is the product key I use to install Windows XP. Weird how that happened.

**Comment by yum13241** [comment]
The archive.org version is a bit corrupted I believe. 7Zip says `WARNING: There is some data after the end of payload data.` which means that the ISO is non-standard. I'll get to work on fixing the WPA problem, since I have the time (by starting all over). Since you already released 1.2, I'll just call it 1.2.1 or something.

**Comment by AFellowSpeedrunner** [comment]
Well, there has been some signs of my hard drive I am using to store my ISO files failing on me. That could be it. Thanks for helping with the .bat file problem as well. I'll be sure to add credits again in the new release.

**Comment by yum13241** [comment]
OK. Btw I've used the same archive.org link before and i had the same result. The one on Enderman's website is better. If you want me to use that version, please tell me what boxes you check for everything before the unattended part. That way I can effectively remake it off of the non corrupted version.

**Comment by AFellowSpeedrunner** [comment]
If you want to take it and make it a full customized Windows distro go ahead! I'm more than happy for TinyXP to be repurposed as that! I think of it like Gentoo, you can customize it from a shell to an entire personalised experience! Only in this case, it would be a entire personalised XPerience.

I'm gonna test the new build now and let you know the results!

**Comment by yum13241** [comment]
> If you want to take it and make it a full customized Windows distro go ahead! I'm more than happy for TinyXP to be repurposed as that! 

Thanks. Btw I'll keep my MEGA link just in case something happens to this repo. Now if only I could add themes back. Or better yet, I just start all over lol, so it isn't based off of an ISO that doesn't extract properly. Your work is appreciated either way.

Now this issue can finally be put to rest.

**Comment by AFellowSpeedrunner** [comment]
> Your work is appreciated either way.
Thanks very much! I originally actually started this when messing around with nLite going "i wonder what happens if i remove everything from XP?" then it turned into an actual project.

> Btw in the release notes it says "This build was remastered with a new ISO!" when it wasn't. Maybe I will over the weekend...
Let me remove that quickly, sorry about that!

**Comment by AFellowSpeedrunner** [comment]
This is great! I'm currently out right now, so I'll get it tested and uploaded later or either tomorrow. (It's 18:40 for me right now.) I thank you greatly for all of your hard work!

**Comment by yum13241** [comment]
You're welcome.

**Comment by AFellowSpeedrunner** [comment]
Weird, in the older versions I had that happen at release, sometimes the product key wouldn't work.

**Comment by AFellowSpeedrunner** [comment]
I got it out! V2.0 is officially out!!!

**Comment by yum13241** [comment]
Closed as complete since it's out. Thanks!

**Comment by AFellowSpeedrunner** [comment]
No problem!
