### ISSUE TITLE
Generic ACPI Battery not autoinstalled, Battery monitoring not functioning, Battery listed as Unknown Plug And Play

### ISSUE THREAD

**Issue by about1437rats** [AFellowSpeedrunner/SmolXP#6]
Hi, i really do like this, especially compared to TinyXP which was comparatively much more of a headache to get running. However, there is one problem, and that's that i haven't been able to get the battery monitoring to work, and battery life was a big reason for going with this specific build. I'm using an MSI Wind u100. Default XP as well as TinyXP detects it as an ACPI compliant battery and are able to monitor it, but SmolXP does not, it shows up as a generic unknown plug and play device, and any ACPI driver option i select does not work. I've already scoured about every inch of google to see if i could slipstream the windows preinstalled ACPI driver, but no luck. Any ideas?

**Comment by yum13241** [comment]
I believe I may have removed it. Do previous versions work? (I am the author of the 2.0 version)


Keep in mind this build has almost no functionality, since I couldn't even install VC Redists.

**Comment by AFellowSpeedrunner** [comment]
Hey, I am the creator of the SmolXP project. 

You might to grab the driver from Windows XP install CD, or from an already installed copy of XP. I tested this VM hardware but not on real hardware yet so I didn't think this happen. I'm assuming somewhere along the way, we removed the ACPI battery driver. I could go searching for it and upload it here.

**Comment by AFellowSpeedrunner** [comment]
@about1437rats 
I got the driver that you may need. Don't know if it's the exact one but it should work. Drop it in the C:\Windows\System32\Drivers folder. I don't know much about Windows drivers but this should hopefully just work.

https://drive.google.com/file/d/1JENImcSL4SP8kcvS3eb9k3bXqFyrjNXi/view?usp=sharing

**Comment by about1437rats** [comment]
Awesome, ill try this ASAP. Will update soon.

**Comment by AFellowSpeedrunner** [comment]
Perfect, can't wait for the results!

**Comment by about1437rats** [comment]
[SMOLXP.LOG](https://github.com/AFellowSpeedrunner/SmolXP/files/13944329/SMOLXP.LOG)
 Here is the hwinfo log, if that helps anything.

**Comment by AFellowSpeedrunner** [comment]
Sorry for the long silence, I kind of forgot. Turns out that when I looked at the config file, battery stuff I think was removed. I am going to try and make an updated version available either tomorrow or soon depending on how busy I am with things. Thanks for the patience though. I am again sorry for forgetting this was still ongoing.

**Comment by about1437rats** [comment]
It would also be okay to have two different "flavors", like, this new one to be a laptop flavor and the old one be a desktop flavor. Its okay, i also kinda forgot... oops. No rush.

**Comment by AFellowSpeedrunner** [comment]
Thanks. I will attempt to try and make two flavors soon. One desktop oriented and one laptop oriented. It's a really good idea in my opinion. Thank you for the idea!

**Comment by AFellowSpeedrunner** [comment]
Please take a look at the readme file, thank you.
