### ISSUE TITLE
Problems with booting on physical machine

### ISSUE THREAD

**Issue by czarnikjak** [AFellowSpeedrunner/SmolXP#7]
I am struggling to boot the installer on a physical laptop (no floppy, no cd drive, only USB storage available for external boot).

Not sure if I am missing something simple,
Burned ISO to USB stick, not bootable and contents of it are not visible from DOS (I cant see a setup.exe file on the iso anyway so I doubt I could start the install from DOS anyway)
Burned that little image found in [boot] folder to USB stick, again not bootable from USB on my laptop.

Any pointers on how to boot it on EEE PC 901 or similar would be appreciated.

**Comment by AFellowSpeedrunner** [comment]
Have you made sure that your download didn't corrupt? Usually it boots fine for me.

**Comment by about1437rats** [comment]
> I am struggling to boot the installer on a physical laptop (no floppy, no cd drive, only USB storage available for external boot).
> 
> Not sure if I am missing something simple, Burned ISO to USB stick, not bootable and contents of it are not visible from DOS (I cant see a setup.exe file on the iso anyway so I doubt I could start the install from DOS anyway) Burned that little image found in [boot] folder to USB stick, again not bootable from USB on my laptop.
> 
> Any pointers on how to boot it on EEE PC 901 or similar would be appreciated.

I ran into something a bit similar when i installed this on my msi Wind u100. I made a bootable USB using rufus, but the installer would always complain something was missing. then, i grabbed my USB dvd drive, burned a CD with the iso on my main pc, and that worked flawlessly.

**Comment by czarnikjak** [comment]
Yes,this iso seems to be only compatible with making bootable cd/DVD drives , not USB.
When I mount the same iso to virtual machine as a cd drive it boots Ok. Not when burned to usb stick though.

**Comment by AFellowSpeedrunner** [comment]
Well, as long as CD's work. I mean, I don't really understand why USB's wouldn't work but I guess it's probably due to driver removals in SmolXP.

**Comment by yum13241** [comment]
I think it also has to do with the fact that computers didn't USB boot in the XP days AFAIK.
Also, ISOs meant for a USB stick have some, let's just say, *special*, treatment.

**Comment by AFellowSpeedrunner** [comment]
Exactly. You were expected to have a CD reader with a copy of XP (or in this case SmolXP) on disk or you can't install. You could do it if you were already in Windows. USB ISO's aren't that hard to create but it is different to making CD ISO's sometimes. I'd suggest making a bootloader on the USB (maybe Ventoy or some alternative) and putting the installer on there making it bootable, or just put GRUB on the USB or something.

**Comment by yum13241** [comment]
USB ISOs would mean having to make friggin' `syslinux` boot Windows XP.

(Look up `isohybrid`)

**Comment by AFellowSpeedrunner** [comment]
> USB ISOs would mean having to make friggin' `syslinux` boot Windows XP.
> 
> 
> 
> (Look up `isohybrid`)


Oh yeah, I forgot that existed! I'll look it up soon.

**Comment by yum13241** [comment]
You may or may not need to replace the boot sector in nLite (the little image in `[BOOT]`).

**Comment by AFellowSpeedrunner** [comment]
I see, thank you.

**Comment by AFellowSpeedrunner** [comment]
Please take a look at the readme file, thank you.

**Comment by AFellowSpeedrunner** [comment]
*resent because I forgot to close the issue with the comment and I don't think I can close with sending a comment, I apologise*

Please take a look at the readme file, thank you.

**Comment by ASDownloadingAccount** [comment]
> I'd suggest making a bootloader on the USB (maybe Ventoy or some alternative) and putting the installer on there making it bootable, or just put GRUB on the USB or something.

Another solution is to use **WinSetupFromUSB** which is GRUB4DOS and select the option 'Windows XP/2000/2003 Setup'.
If you have Ventoy on the USB, add [Easy2Boot](https://easy2boot.xyz/ventoy/add-easy2boot-to-a-ventoy-usb-drive).
